# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "主页"
  url = "/"
  weight = 10

[[main]]
  name = "Istio 基础"
  url = "/basics/"
  weight = 20
